// DSX sandbox — mock registry. One file per module; the first registered match wins, so import specific modules first.
// Generated by `sandbox.mjs init`; filled by the mock-writing step of the `sandbox` skill.
import './example';
