#!/usr/bin/env node
// DSX sandbox — launcher for the npm scripts (`node sandbox/cli.mjs dev`). Finds the project (the folder above with
// .dsx/config.json) and the DSX (env DSX_ROOT, else sandbox.dsx_root in that config), then runs
// <DSX>/tools/sandbox/sandbox.mjs <command> --root <project>. Generated by `sandbox.mjs init`.
import { existsSync, readFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

let root = dirname(fileURLToPath(import.meta.url));
while (!existsSync(join(root, '.dsx', 'config.json'))) {
  const up = dirname(root);
  if (up === root) { console.error('dsx sandbox: no .dsx/config.json above this folder'); process.exit(3); }
  root = up;
}
const cfg = JSON.parse(readFileSync(join(root, '.dsx', 'config.json'), 'utf8'));
const dsx = process.env.DSX_ROOT || cfg.sandbox?.dsx_root;
const cli = dsx ? join(resolve(root, dsx), 'tools', 'sandbox', 'sandbox.mjs') : null;
if (!cli || !existsSync(cli)) {
  console.error(`dsx sandbox: DSX not found${dsx ? ` at ${dsx}` : ''}. Set DSX_ROOT to the DSX folder, or sandbox.dsx_root in .dsx/config.json.`);
  process.exit(3);
}
const r = spawnSync(process.execPath, [cli, ...process.argv.slice(2), '--root', root], { stdio: 'inherit' });
process.exit(r.status ?? 1);
