// DSX sandbox — separate Vite build that serves the MIRROR (an isolated copy of the UI code), never the official src/.
// Generated by `sandbox.mjs init`; settings come from the "sandbox" block of .dsx/config.json (lib/settings.ts).
//
// - The app's real entry runs from the mirror (`@dsx-entry`), so providers, routes and styles are the production ones.
// - Modules listed in sandbox.swaps (the auth module) are replaced by resolved path, not by import specifier.
// - API base env vars become same-origin prefixes (/__dsx/<base>) answered by the mocks; identity settings are blanked.
// - The design-lab manifest is built live from the mirror's DESIGN.md and design options (id without a .json suffix:
//   Vite's JSON plugin would re-process the module; directories are watched through server.watcher, not addWatchFile).
// - fs.allow is the sandbox folder and node_modules: the official src/ is refused by the dev server.
import { defineConfig, type Plugin } from 'vite';
import { existsSync } from 'node:fs';
import { dirname, join, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
// @dsx:plugin-imports
import react from '@vitejs/plugin-react';
// @dsx:end
import { buildManifest } from './lib/manifest';
import { loadSettings } from './lib/settings';

const here = dirname(fileURLToPath(import.meta.url));
const S = loadSettings(here);
if (!existsSync(join(S.mirrorDir, '.dsx-base.json'))) {
  throw new Error('dsx sandbox: no mirror yet — run `node <DSX>/tools/sandbox/sandbox.mjs sync` (or `dev`, which ensures it)');
}
const MANIFEST_ID = '\0dsx-sandbox-design-options';

function swapModules(): Plugin {
  const replacements = new Set(Object.values(S.swaps));
  return {
    name: 'dsx-sandbox-swap',
    enforce: 'pre',
    async resolveId(source, importer, options) {
      if (!importer || replacements.has(importer)) return null; // a replacement may import the module it replaces
      for (const r of S.redirects) if (source === r.specifier && importer.startsWith(r.importer_prefix)) return r.to;
      const resolved = await this.resolve(source, importer, { ...options, skipSelf: true });
      if (!resolved) return null;
      if (S.design.manifest && resolved.id === S.design.manifest) return MANIFEST_ID;
      return S.swaps[resolved.id] ?? null;
    },
  };
}

function liveManifest(): Plugin {
  const build = () => buildManifest({ root: S.mirrorDir, official: S.design.official, optionsDir: S.design.optionsDir, active: S.design.active });
  return {
    name: 'dsx-sandbox-design-manifest',
    load(id) {
      return id === MANIFEST_ID ? `export default ${JSON.stringify(build())};` : null;
    },
    configureServer(server) {
      server.watcher.add([S.design.official, S.design.optionsDir]);
      const changed = (file: string) => {
        if (file !== S.design.official && !file.startsWith(S.design.optionsDir + sep)) return;
        const mod = server.moduleGraph.getModuleById(MANIFEST_ID);
        if (mod) server.moduleGraph.invalidateModule(mod);
        server.ws.send({ type: 'full-reload' });
      };
      for (const event of ['change', 'add', 'unlink'] as const) server.watcher.on(event, changed);
    },
  };
}

export default defineConfig({
  root: here,
  publicDir: S.publicDir ?? false,
  plugins: [swapModules(), liveManifest(), /* @dsx:plugins */ react() /* @dsx:end */],
  resolve: {
    alias: [
      { find: '@dsx-entry', replacement: S.entry },
      ...Object.entries(S.aliases).map(([find, replacement]) => ({ find, replacement })),
    ],
  },
  define: S.define,
  server: {
    host: '127.0.0.1',
    port: S.ports.dev,
    strictPort: true,
    fs: { strict: true, allow: [here, join(S.packageDir, 'node_modules'), join(S.root, 'node_modules')] },
  },
  preview: { host: '127.0.0.1', port: S.ports.preview, strictPort: true },
  build: { outDir: join(here, 'dist'), emptyOutDir: true, sourcemap: true },
});
