#!/usr/bin/env node
// Compiles the DTCG tokens (tokens/*.tokens.json) into CSS custom properties and resolved JSON,
// and checks the contrast pairs declared in tokens/contrast-pairs.json for each theme.
// Usage: node tools/build-tokens.mjs [--tokens <folder>] [--check]
//   --tokens: folder with primitives/semantic.light/semantic.dark[/component].tokens.json and contrast-pairs.json
//             (default: the DSX tokens/). Use it to compile a project's tokens.
//   --check:  validate only, write no files. Output goes to <folder>/build/.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { contrast } from './lib/color.mjs';
import { parseArgs } from './lib/cli.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
let DIR = join(ROOT, 'tokens');
/** Points the build at another tokens folder (e.g. the user's project). */
export const useTokensDir = (dir) => { DIR = dir; };
const T = (f) => join(DIR, f);
const read = (f) => JSON.parse(readFileSync(T(f), 'utf8'));

/** Flattens the DTCG tree into { "a.b.c": { value, type, description } }. */
export function flatten(tree, prefix = '', out = {}, inheritedType) {
  for (const [k, v] of Object.entries(tree)) {
    if (k.startsWith('$')) continue;
    const path = prefix ? `${prefix}.${k}` : k;
    const type = v.$type ?? inheritedType;
    if (v && typeof v === 'object' && '$value' in v) out[path] = { value: v.$value, type, description: v.$description };
    else if (v && typeof v === 'object') flatten(v, path, out, type);
  }
  return out;
}

/** Resolves {a.b.c} aliases recursively, detecting cycles. */
export function resolve(flat) {
  const done = {};
  const visit = (path, stack = []) => {
    if (path in done) return done[path];
    if (stack.includes(path)) throw new Error(`Circular alias: ${[...stack, path].join(' -> ')}`);
    const tok = flat[path];
    if (!tok) throw new Error(`Reference to a missing token: ${path} (via ${stack.at(-1)})`);
    let v = tok.value;
    if (typeof v === 'string') {
      const whole = v.match(/^\{([^}]+)\}$/);
      if (whole) v = visit(whole[1], [...stack, path]);
      else v = v.replace(/\{([^}]+)\}/g, (_, p) => visit(p, [...stack, path]));
    }
    return (done[path] = v);
  };
  for (const p of Object.keys(flat)) visit(p);
  return done;
}

const cssName = (path) => '--' + path.replace(/\./g, '-');

function cssValue(v, type) {
  if (type === 'fontFamily' && Array.isArray(v)) return v.map((f) => (/\s/.test(f) ? `"${f}"` : f)).join(', ');
  if (type === 'cubicBezier' && Array.isArray(v)) return `cubic-bezier(${v.join(', ')})`;
  if (type === 'shadow' && typeof v === 'object') return `${v.offsetX} ${v.offsetY} ${v.blur} ${v.spread} ${v.color}`;
  return String(v);
}

function block(selector, resolved, flat, keys) {
  const lines = keys.map((k) => `  ${cssName(k)}: ${cssValue(resolved[k], flat[k].type)};`);
  return `${selector} {\n${lines.join('\n')}\n}\n`;
}

export function build() {
  const prim = flatten(read('primitives.tokens.json'));
  const light = flatten(read('semantic.light.tokens.json'));
  const dark = flatten(read('semantic.dark.tokens.json'));
  const comp = existsSync(T('component.tokens.json')) ? flatten(read('component.tokens.json')) : {};
  const all = { light: { ...prim, ...light, ...comp }, dark: { ...prim, ...light, ...dark, ...comp } };
  const resolved = { light: resolve(all.light), dark: resolve(all.dark) };

  const missingInDark = Object.keys(dark).filter((k) => !(k in light));
  if (missingInDark.length) throw new Error(`Dark theme defines keys missing from the light theme: ${missingInDark.join(', ')}`);

  const semanticKeys = [...Object.keys(light), ...Object.keys(comp)];
  // Component tokens point at semantic ones; in the dark theme they are re-emitted to resolve the new values.
  const darkKeys = [...Object.keys(dark), ...Object.keys(comp)];
  const css =
    `/* Generated by tools/build-tokens.mjs. Do not edit by hand. */\n` +
    block(':root', resolved.light, all.light, [...Object.keys(prim), ...semanticKeys]) +
    `\n@media (prefers-color-scheme: dark) {\n` +
    block(':root:not([data-theme="light"])', resolved.dark, all.dark, darkKeys).replace(/^/gm, '  ') +
    `}\n\n` +
    block(':root[data-theme="dark"]', resolved.dark, all.dark, darkKeys);

  return { css, resolved };
}

export function checkContrast(resolved) {
  const pairs = JSON.parse(readFileSync(T('contrast-pairs.json'), 'utf8'));
  // Compatible read (2026-10 transition): old key "uso" → "use".
  if (pairs.some((p) => p.uso !== undefined && p.use === undefined)) {
    console.warn('WARNING  contrast-pairs.json: key "uso" is an old name, rename it to "use" (docs/renames-2026-10.md).');
    for (const p of pairs) if (p.use === undefined && p.uso !== undefined) { p.use = p.uso; delete p.uso; }
  }
  const results = [];
  for (const theme of Object.keys(resolved)) {
    for (const p of pairs) {
      const fg = resolved[theme][p.fg], bg = resolved[theme][p.bg];
      if (!fg || !bg) throw new Error(`Contrast pair references a missing token: ${p.fg} / ${p.bg}`);
      // Skips colors with alpha (8 digits): contrast depends on what is behind them.
      if (fg.length > 7 || bg.length > 7) continue;
      const ratio = contrast(fg, bg);
      results.push({ theme, ...p, ratio: +ratio.toFixed(2), ok: ratio >= (p.min ?? 4.5) });
    }
  }
  return results;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const args = parseArgs();
  if (args.tokens) useTokensDir(args.tokens);
  const { css, resolved } = build();
  const results = checkContrast(resolved);
  for (const r of results) {
    console.log(`${r.ok ? 'OK  ' : 'FAIL'} [${r.theme}] ${r.ratio}:1 (min ${r.min}) ${r.fg} / ${r.bg} — ${r.use}`);
  }
  const fails = results.filter((r) => !r.ok);
  if (!args.check) {
    mkdirSync(T('build'), { recursive: true });
    writeFileSync(T('build/tokens.css'), css);
    writeFileSync(T('build/tokens.light.json'), JSON.stringify(resolved.light, null, 2) + '\n');
    writeFileSync(T('build/tokens.dark.json'), JSON.stringify(resolved.dark, null, 2) + '\n');
    console.log(`\nGenerated: ${T('build')}/tokens.css, tokens.light.json, tokens.dark.json`);
  }
  if (fails.length) {
    console.error(`\n${fails.length} contrast pair(s) below the minimum.`);
    process.exit(1);
  }
}
