// Interface strings of the pages generated by the ux-lint (text-page.mjs, findings.mjs page, audit.mjs --page) and of
// the text drawn on the option previews (preview.mjs). `--lang en|pt-BR` picks the dictionary; default `en`. The
// pt-BR dictionary preserves the pages exactly as they were before the English default.
//
// Two languages are involved and they are not the same thing:
// - the page language (`--lang`): chrome, labels, annotations drawn over the capture, image alt text;
// - the product language (UX.md `content.language`, lib/lang/): text the previews put INSIDE the product
//   (state blocks, region titles, plain words for technical terms). See PRODUCT_TEXT below.
import { resolveLang } from './lang/index.mjs';

export const PAGE_LANGS = ['en', 'pt-BR'];
export const DEFAULT_PAGE_LANG = 'en';

/** Normalizes `--lang` (en, en-US, pt, pt-br…). Omitted → en. Unknown → throws with a clear message. */
export function pageLang(tag) {
  if (tag === undefined || tag === null || tag === true || tag === '') return DEFAULT_PAGE_LANG;
  const l = resolveLang(tag);
  if (!l) throw new Error(`unknown --lang "${tag}" (use ${PAGE_LANGS.join(' or ')})`);
  return l;
}

const plural = (n, one, many) => (n === 1 ? one : many);

const EN = {
  htmlLang: 'en',
  // ---------- text-page.mjs ----------
  element: {
    button: 'Buttons', title: 'Titles', label: 'Field labels', tooltip: 'Hints (tooltip)', helper: 'Descriptions and helper text',
    alert: 'Alerts and messages', placeholder: 'Text inside the field', tab: 'Tabs', 'accessible-name': 'Accessible names', cell: 'Table cells', menu: 'Menu items',
    screen: 'Screen (structure)', flow: 'Flow', states: 'States', layout: 'Layout and hierarchy', consistency: 'Consistency across screens',
  },
  rule: {
    X1: 'dash', X1b: 'dash as empty value', X2: 'compound title', X3: 'redundant description', X4: 'empty opening',
    X5: 'final punctuation', X6: 'long button or no verb', X7: 'redundant or long hint', X8: 'placeholder repeats label',
    X9: 'explanatory parenthesis', X10: 'Title Case', X11: 'technical term', desc: 'unnecessary description',
  },
  removed: 'removed',
  compareWithToday: 'Compare with today', before: 'Before', after: 'After', zoom: 'Enlarge',
  noPreview: 'No preview', recommended: 'recommended', ruleFix: 'Fix indicated by the rule', today: 'Today', also: 'Also',
  severity: (n) => `severity ${n} of 4`, whyRecommended: 'Why the recommended one:',
  screens: (n) => `${n} ${plural(n, 'screen', 'screens')}:`,
  pagesNav: 'Pages', prev: '← Previous', next: 'Next →', page: 'Page',
  indexLine: (i, n, groups) => `Page ${i}</a>: ${n} ${plural(n, 'case', 'cases')} · ${groups}`,
  imageMissing: 'missing image', titleDefault: 'Screen text', pageOf: (n, m) => ` · page ${n} of ${m}`,
  eyebrowDefault: 'Interface text survey',
  ledeDefault: 'Each case shows the element as it appears today and the text options, rendered in the same style. The tag on each option says which convention it comes from. The source in the code shows where to fix it.',
  nCases: (n) => `<b>${n}</b> ${plural(n, 'case', 'cases')}`, nOptions: (n) => `<b>${n}</b> ${plural(n, 'option', 'options')}`,
  nSev2: (n) => `<b>${n}</b> of severity 2 or more`, nScreens: (n) => `<b>${n}</b> ${plural(n, 'screen', 'screens')} affected`,
  pageCount: (n, m, k) => `page <b>${n}</b> of ${m} (${k} ${plural(k, 'case', 'cases')})`,
  filterBy: 'Filter by element', enlarged: 'Enlarged image', close: 'Close',
  // ---------- findings.mjs page ----------
  status: { open: 'open', decided: 'decided', ignored: 'ignored', 'accepted-deviation': 'accepted deviation', fixed: 'fixed', regression: 'regression' },
  deviation: (id, by, until, reason) => `<strong>Accepted deviation ${id}</strong> (declared in UX.md${by ? `, decided by ${by}` : ''}${until ? `, valid until ${until}` : ''}): ${reason}. To reopen it, remove the deviation from UX.md and register again.`,
  decided: (what, by, at) => `Decided: ${what}${by ? ` by ${by}` : ''}${at ? ` on ${at}` : ''}`,
  decidedIgnore: 'ignore', decidedFree: (t) => `free text "${t}"`, decidedOption: (l) => `option ${l}`,
  yourDecision: 'Your decision', ignore: 'Ignore', reason: 'Reason', reasonPlaceholder: 'Reason (required to ignore)',
  whoDecides: 'Who decides', copyDecisions: 'Copy decisions', decisionsJson: 'Decisions in JSON',
  findingsTitle: (m) => `UX findings · ${m}`, findingsEyebrow: 'UX findings register',
  findingsLede: (withPreview, fixed, accepted) => `Each case shows the element as it appears today and the options${withPreview ? ', with the preview taken from the real capture of the screen (before and after, with the element outlined; click to enlarge and use Before | After to compare in the same place)' : ''}. Pick an option or "Ignore" (with a reason) and use "Copy decisions" at the end of the page: the JSON, with the decisions of every page, goes to decisions.json through the import command. ${fixed} fixed ${plural(fixed, 'finding was', 'findings were')} left out of the list.${accepted ? ` ${accepted} ${plural(accepted, 'finding', 'findings')} covered by a deviation declared in UX.md appear with the reason and do not count as open.` : ''}`,
  // embedded script (strings only; the script reads them from a JSON block)
  script: {
    counter: '{n} decided of {total}',
    needReason: 'To ignore, write the reason ({n} case(s) without a reason{other}; the ones on this page are in red).',
    otherPages: ', some on other pages',
    copied: '{n} decision(s) from every page copied. Paste them into decisions.json or into the chat.',
    selectToCopy: '{n} decision(s) in the field below, already selected: copy with Ctrl+C or Cmd+C.',
    owner: 'owner',
  },
  // ---------- previews: alt text on the page (lib/preview-page.mjs) ----------
  target: {
    element: { button: 'button', title: 'title', label: 'label', helper: 'helper text', alert: 'alert', tab: 'tab', menu: 'menu item', cell: 'cell', placeholder: 'text inside the field' },
    flow: (s) => `transitions of the screen "${s}" in the flow map`, screen: (s) => `screen ${s}`, el: (el, t, s) => `${el} "${t}" on the screen ${s}`,
  },
  stale: 'outdated preview: the capture changed after it was generated; run preview.mjs again',
  altBefore: (t, outlined) => `Today: ${t}${outlined ? ', outlined in red' : ''}`,
  altRuleWho: (l) => `Fix indicated by the rule (${l})`, altOptionWho: (l) => `Option ${l}`,
  altAfter: (who, d, outlined) => `${who} applied: ${d}${outlined ? '; changed element outlined in green' : ''}`,
  // ---------- previews: labels drawn and stored in the manifest (lib/preview-spec.mjs, preview.mjs) ----------
  badgeNoChange: 'No change', badgeAlready: 'Already like this on this screen',
  proposal: 'Proposal built with components of the screen itself',
  kind: {
    text: 'Text replaced', remove: 'Element removed', variant: 'Button weight changed', move: 'Element moved', themeSize: 'Size on the theme scale',
    style: 'Style adjusted', annTooltip: 'Annotation: hint', ann: 'Annotation', annSr: 'Annotation: screen reader', example: 'Example from another screen', flow: 'Flow diagram',
  },
  ops: {
    text: (t) => `text replaced by "${t}"`, remove: 'element removed',
    variant: (all, v) => `${all ? 'other buttons' : 'button'} in the ${v} variant`,
    moveTo: { end: 'moved to the end of the group', start: 'moved to the start of the group', 'region-top': 'moved inside the first fold' },
    justify: (j) => `group aligned (${j})`, style: (s) => `style ${s}`, align: 'left edges aligned',
    replaceMany: (p) => `texts replaced (${p})`,
    insert: (like, from, t) => `inserted ${like ? `(${like})` : `from ${from ?? 'this capture'}`}${t ? ` with "${t}"` : ''}`,
    wrap: (t) => `grouped in a container${t ? ` "${t}"` : ''}`,
    annotate: { tooltip: 'hint', hint: 'note', 'screen-reader': 'screen reader' },
    badge: (t) => `badge "${t}"`, state: (s) => `state "${s}" built on the screen`, region: (r) => `region "${r}" built on the screen`, example: (s) => `example from the capture ${s}`,
  },
  implicit: {
    L1: 'Primary action at the end of the group, aligned right', L3: 'Titles on the theme scale (higher level, larger text)',
    L4: 'Left edges aligned to the columns of the group', L6: 'Primary action inside the first fold', L7: 'Line limited to about 72 characters',
    L8: (n) => `Target of at least ${n}×${n} px`, L9: (r) => `Region "${r}" built on the screen`,
    C2: (v) => `Same weight as the majority (${v} variant)`, C1: (k) => `Same label on every screen ("${k}", the first one cited)`,
    S1: (s) => `State "${s}" built on the screen itself`, S1example: (ex, s) => `How the screen ${ex} shows the state "${s}"`,
    T1: 'One primary per region: the others outlined', T3: 'Main title as h1, on the theme scale', T3sr: 'Title, level 1: {self}',
    T6: (t, p) => (p ? `"${t}" replaced by "${p}"` : `"${t}" removed from the text`), T7: 'Verb + object (the object comes from the nearest label)',
    X9: 'Without the explanatory parenthesis', X2: 'One block in the title, the other in helper text right below', X6long: 'Only the first block (up to 4 words)',
    X6obj: 'Verb + object (the object comes from the nearest label)',
    F1: 'With an exit', F2: 'Inside a journey', F5: 'With a way back',
  },
  flow: { screens: 'screens', noEntry: 'no entry in the map', noExit: 'no exit', backTo: (n) => `back to ${n}`, declared: 'journey declared in the map (to be defined)', outside: 'outside every journey of the map' },
  // ---------- previews: drawn inside the capture by lib/preview-runtime.mjs ----------
  runtime: {
    screenReader: 'Screen reader', fold: (px) => `fold (${px} px)`, belowFold: (t, px) => `↓ «${t}» is below the fold, ${px} px from the top`,
    regionShell: 'Region expected by the archetype; the content depends on the decision.',
  },
};

const PT = {
  htmlLang: 'pt-BR',
  element: {
    button: 'Botões', title: 'Títulos', label: 'Rótulos de campo', tooltip: 'Dicas (tooltip)', helper: 'Descrições e textos de apoio',
    alert: 'Alertas e mensagens', placeholder: 'Textos dentro do campo', tab: 'Abas', 'accessible-name': 'Nomes acessíveis', cell: 'Células de tabela', menu: 'Itens de menu',
    screen: 'Tela (estrutura)', flow: 'Fluxo', states: 'Estados', layout: 'Layout e hierarquia', consistency: 'Consistência entre telas',
  },
  rule: {
    X1: 'travessão', X1b: 'travessão como vazio', X2: 'título composto', X3: 'descrição redundante', X4: 'abertura vazia',
    X5: 'pontuação final', X6: 'botão longo ou sem verbo', X7: 'dica redundante ou longa', X8: 'placeholder repete rótulo',
    X9: 'parêntese explicativo', X10: 'Caixa De Título', X11: 'termo técnico', desc: 'descrição desnecessária',
  },
  removed: 'removido',
  compareWithToday: 'Comparar com hoje', before: 'Antes', after: 'Depois', zoom: 'Ampliar',
  noPreview: 'Sem prévia', recommended: 'recomendada', ruleFix: 'Correção indicada pela regra', today: 'Hoje', also: 'Também',
  severity: (n) => `severidade ${n} de 4`, whyRecommended: 'Por que a recomendada:',
  screens: (n) => `${n} tela(s):`,
  pagesNav: 'Páginas', prev: '← Anterior', next: 'Próxima →', page: 'Página',
  indexLine: (i, n, groups) => `Página ${i}</a>: ${n} caso(s) · ${groups}`,
  imageMissing: 'imagem ausente', titleDefault: 'Texto das telas', pageOf: (n, m) => ` · página ${n} de ${m}`,
  eyebrowDefault: 'Levantamento de texto de interface',
  ledeDefault: 'Cada caso mostra o elemento como aparece hoje e as opções de texto, renderizadas no mesmo estilo. A etiqueta de cada opção diz de que convenção ela vem. A origem no código indica onde corrigir.',
  nCases: (n) => `<b>${n}</b> casos`, nOptions: (n) => `<b>${n}</b> opções`,
  nSev2: (n) => `<b>${n}</b> de severidade 2 ou mais`, nScreens: (n) => `<b>${n}</b> telas afetadas`,
  pageCount: (n, m, k) => `página <b>${n}</b> de ${m} (${k} casos)`,
  filterBy: 'Filtrar por elemento', enlarged: 'Imagem ampliada', close: 'Fechar',
  status: { open: 'aberto', decided: 'decidido', ignored: 'ignorado', 'accepted-deviation': 'desvio aceito', fixed: 'corrigido', regression: 'regressão' },
  deviation: (id, by, until, reason) => `<strong>Desvio aceito ${id}</strong> (declarado no UX.md${by ? `, decidido por ${by}` : ''}${until ? `, vale até ${until}` : ''}): ${reason}. Para reabrir, tire o desvio do UX.md e registre de novo.`,
  decided: (what, by, at) => `Decidido: ${what}${by ? ` por ${by}` : ''}${at ? ` em ${at}` : ''}`,
  decidedIgnore: 'ignorar', decidedFree: (t) => `texto livre "${t}"`, decidedOption: (l) => `opção ${l}`,
  yourDecision: 'Sua decisão', ignore: 'Ignorar', reason: 'Motivo', reasonPlaceholder: 'Motivo (obrigatório para ignorar)',
  whoDecides: 'Quem decide', copyDecisions: 'Copiar decisões', decisionsJson: 'Decisões em JSON',
  findingsTitle: (m) => `Achados de UX · ${m}`, findingsEyebrow: 'Registro de achados de UX',
  findingsLede: (withPreview, fixed, accepted) => `Cada caso mostra o elemento como aparece hoje e as opções${withPreview ? ', com a prévia tirada da captura real da tela (antes e depois, com o elemento contornado; clique para ampliar e use Antes | Depois para comparar no mesmo lugar)' : ''}. Escolha uma opção ou "Ignorar" (com motivo) e use "Copiar decisões" no fim da página: o JSON, com as decisões de todas as páginas, vai para decisions.json pelo comando import. ${fixed} achado(s) corrigido(s) ficaram fora da lista.${accepted ? ` ${accepted} achado(s) cobertos por desvio declarado no UX.md aparecem com o motivo e não contam como abertos.` : ''}`,
  script: {
    counter: '{n} decididos de {total}',
    needReason: 'Para ignorar, escreva o motivo ({n} caso(s) sem motivo{other}; os desta página estão em vermelho).',
    otherPages: ', alguns em outras páginas',
    copied: '{n} decisão(ões) de todas as páginas copiadas. Cole em decisions.json ou no chat.',
    selectToCopy: '{n} decisão(ões) no campo abaixo, já selecionadas: copie com Ctrl+C ou Cmd+C.',
    owner: 'dono',
  },
  target: {
    element: { button: 'botão', title: 'título', label: 'rótulo', helper: 'texto de apoio', alert: 'alerta', tab: 'aba', menu: 'item de menu', cell: 'célula', placeholder: 'texto dentro do campo' },
    flow: (s) => `transições da tela "${s}" no mapa de fluxo`, screen: (s) => `tela ${s}`, el: (el, t, s) => `${el} "${t}" na tela ${s}`,
  },
  stale: 'prévia desatualizada: a captura mudou depois de gerada; rode preview.mjs de novo',
  altBefore: (t, outlined) => `Hoje: ${t}${outlined ? ', contornado em vermelho' : ''}`,
  altRuleWho: (l) => `Correção indicada pela regra (${l})`, altOptionWho: (l) => `Opção ${l}`,
  altAfter: (who, d, outlined) => `${who} aplicada: ${d}${outlined ? '; elemento alterado contornado em verde' : ''}`,
  badgeNoChange: 'Sem mudança', badgeAlready: 'Já está assim nesta tela',
  proposal: 'Proposta montada com componentes da própria tela',
  kind: {
    text: 'Texto trocado', remove: 'Elemento removido', variant: 'Peso do botão trocado', move: 'Elemento movido', themeSize: 'Tamanho na escala do tema',
    style: 'Estilo ajustado', annTooltip: 'Anotação: dica', ann: 'Anotação', annSr: 'Anotação: leitor de tela', example: 'Exemplo de outra tela', flow: 'Diagrama do fluxo',
  },
  ops: {
    text: (t) => `texto trocado por "${t}"`, remove: 'elemento removido',
    variant: (all, v) => `${all ? 'demais botões' : 'botão'} na variante ${v}`,
    moveTo: { end: 'movido para o fim do grupo', start: 'movido para o início do grupo', 'region-top': 'movido para dentro da primeira dobra' },
    justify: (j) => `grupo alinhado (${j})`, style: (s) => `estilo ${s}`, align: 'bordas esquerdas alinhadas',
    replaceMany: (p) => `textos trocados (${p})`,
    insert: (like, from, t) => `inserido ${like ? `(${like})` : `de ${from ?? 'esta captura'}`}${t ? ` com "${t}"` : ''}`,
    wrap: (t) => `agrupado num contêiner${t ? ` "${t}"` : ''}`,
    annotate: { tooltip: 'dica', hint: 'anotação', 'screen-reader': 'leitor de tela' },
    badge: (t) => `selo "${t}"`, state: (s) => `estado "${s}" montado na tela`, region: (r) => `região "${r}" montada na tela`, example: (s) => `exemplo da captura ${s}`,
  },
  implicit: {
    L1: 'Ação primária no fim do grupo, alinhada à direita', L3: 'Títulos na escala do tema (nível maior, texto maior)',
    L4: 'Bordas esquerdas alinhadas às colunas do grupo', L6: 'Ação primária dentro da primeira dobra', L7: 'Linha limitada a cerca de 72 caracteres',
    L8: (n) => `Alvo de pelo menos ${n}×${n} px`, L9: (r) => `Região "${r}" montada na tela`,
    C2: (v) => `Mesmo peso da maioria (variante ${v})`, C1: (k) => `Mesmo rótulo em todas as telas ("${k}", o primeiro citado)`,
    S1: (s) => `Estado "${s}" montado na própria tela`, S1example: (ex, s) => `Como a tela ${ex} mostra o estado "${s}"`,
    T1: 'Uma primária por região: as demais em contornado', T3: 'Título principal como h1, na escala do tema', T3sr: 'Título, nível 1: {self}',
    T6: (t, p) => (p ? `"${t}" trocado por "${p}"` : `"${t}" tirado do texto`), T7: 'Verbo + objeto (o objeto vem do rótulo mais próximo)',
    X9: 'Sem o parêntese explicativo', X2: 'Um bloco no título, o outro em apoio logo abaixo', X6long: 'Só o primeiro bloco (até 4 palavras)',
    X6obj: 'Verbo + objeto (o objeto vem do rótulo mais próximo)',
    F1: 'Com uma saída', F2: 'Dentro de uma jornada', F5: 'Com caminho de volta',
  },
  flow: { screens: 'telas', noEntry: 'sem entrada no mapa', noExit: 'sem saída', backTo: (n) => `voltar para ${n}`, declared: 'jornada declarada no mapa (a definir)', outside: 'fora de todas as jornadas do mapa' },
  runtime: {
    screenReader: 'Leitor de tela', fold: (px) => `dobra (${px} px)`, belowFold: (t, px) => `↓ «${t}» está abaixo da dobra, a ${px} px do topo`,
    regionShell: 'Região prevista no arquétipo; o conteúdo depende da decisão.',
  },
};

const DICT = { en: EN, 'pt-BR': PT };

/** Strings of the page language (`--lang`, already normalized or raw). */
export function pageStrings(lang = DEFAULT_PAGE_LANG) {
  return DICT[pageLang(lang)];
}

/** Strings the runtime draws inside the capture (plain data: the runtime is serialized, functions do not travel). */
export function runtimeStrings(lang = DEFAULT_PAGE_LANG) {
  const s = pageStrings(lang).runtime;
  return { screenReader: s.screenReader, fold: s.fold('{px}'), belowFold: s.belowFold('{t}', '{px}'), regionShell: s.regionShell };
}

// ---------- product text (language of the product, UX.md `content.language`; default pt-BR) ----------

const NO_ACCESS_PT = 'Quem concede o acesso é o administrador da sua conta. Peça a ele e recarregue a página.';
const LINK_PT = 'Peça um novo link a quem enviou o pedido.';
const NO_ACCESS_EN = 'Your account administrator grants access. Ask them and reload the page.';
const LINK_EN = 'Ask the person who sent the request for a new link.';

/**
 * Text that the previews put inside the product: state blocks (titles, texts, actions), region titles, the search
 * placeholder and the plain word that replaces a technical term (T6). Follows the feedback policy of the UX.md
 * contract: no-access says who grants it, error says what to do.
 */
export const PRODUCT_TEXT = {
  'pt-BR': {
    state: {
      empty: { title: 'Nada por aqui ainda', text: 'Quando houver itens, eles aparecem aqui.' },
      'empty-filtered': { title: 'Nenhum resultado para estes filtros', text: 'Mude ou limpe os filtros para ver mais itens.', action: 'Limpar filtros' },
      'no-data-in-period': { title: 'Nada neste período', text: 'Escolha outro período para ver os dados.' },
      error: { title: 'Não foi possível carregar', text: 'Não foi possível falar com o servidor agora. Tente de novo em instantes.', action: 'Tentar novamente', dialog: 'Não foi possível concluir agora. O que você preencheu continua aqui; tente de novo.' },
      'no-access': { title: 'Você não tem acesso a esta área', text: NO_ACCESS_PT, dialog: `Você não tem permissão para esta ação. ${NO_ACCESS_PT}` },
      unavailable: { title: 'Este conteúdo não está disponível', text: 'Ele pode ter sido removido. Volte à lista e abra de novo.' },
      'invalid-link': { title: 'Este link não está mais disponível.', text: LINK_PT },
      'expired-link': { title: 'Este link expirou.', text: LINK_PT },
      'already-answered': { title: 'Esta resposta já foi registrada', text: 'Não é preciso responder de novo. Se precisar mudar algo, fale com quem enviou o pedido.' },
      processing: { text: 'Processando… O conteúdo aparece aqui assim que terminar.' },
      partial: { text: 'Parte dos dados não carregou; o que aparece abaixo pode estar incompleto. Tente de novo em instantes.' },
      stale: { text: 'Estes dados podem estar desatualizados. Atualize para ver a situação de agora.' },
      conflict: { text: 'Outra pessoa salvou uma versão mais nova enquanto você editava. Reveja as mudanças antes de salvar.' },
      saved: { text: 'Alterações salvas.' },
      success: { text: 'Pronto. A mudança foi gravada.' },
      'unsaved-changes': { text: 'Há alterações não salvas.' },
      'read-only': { text: 'Somente leitura: você pode ver, mas não editar.' },
      'draft-restored': { text: 'Rascunho recuperado: você continua de onde parou.' },
      'field-error': { text: 'Preencha este campo.' },
      unknown: (s) => `Estado "${s}".`,
    },
    region: {
      'side-panel': 'Painel lateral', 'kpi-strip': 'Indicadores', 'search-bar': 'Busca', 'decision-area': 'Decisão',
      'viewer-toolbar': 'Barra do documento', filters: 'Filtros', 'bulk-actions-bar': 'Ações em lote', toolbar: 'Barra de ações',
      header: 'Cabeçalho', summary: 'Resumo', 'danger-zone': 'Zona de risco', 'quick-view': 'Visualização rápida',
    },
    search: 'Buscar',
    plainTerms: {
      ses: 'e-mail', smtp: 'e-mail', sha256: '', sha1: '', md5: '', hash: '', token: 'código', uuid: 'código',
      payload: 'dados', endpoint: 'endereço', backend: 'servidor', worker: 'processo automático', snapshot: 'versão',
      tenant: 'conta', flag: 'opção', rls: '', is_corrente: '', json: 'arquivo', api: 'integração',
    },
  },
  en: {
    state: {
      empty: { title: 'Nothing here yet', text: 'When there are items, they show up here.' },
      'empty-filtered': { title: 'No results for these filters', text: 'Change or clear the filters to see more items.', action: 'Clear filters' },
      'no-data-in-period': { title: 'Nothing in this period', text: 'Choose another period to see the data.' },
      error: { title: 'Could not load', text: 'We could not reach the server right now. Try again in a moment.', action: 'Try again', dialog: 'Could not finish right now. What you filled in is still here; try again.' },
      'no-access': { title: 'You do not have access to this area', text: NO_ACCESS_EN, dialog: `You do not have permission for this action. ${NO_ACCESS_EN}` },
      unavailable: { title: 'This content is not available', text: 'It may have been removed. Go back to the list and open it again.' },
      'invalid-link': { title: 'This link is no longer available.', text: LINK_EN },
      'expired-link': { title: 'This link has expired.', text: LINK_EN },
      'already-answered': { title: 'This answer was already recorded', text: 'No need to answer again. If you need to change something, contact the person who sent the request.' },
      processing: { text: 'Processing… The content shows up here as soon as it finishes.' },
      partial: { text: 'Part of the data did not load; what you see below may be incomplete. Try again in a moment.' },
      stale: { text: 'This data may be out of date. Refresh to see the current situation.' },
      conflict: { text: 'Someone else saved a newer version while you were editing. Review the changes before saving.' },
      saved: { text: 'Changes saved.' },
      success: { text: 'Done. The change was saved.' },
      'unsaved-changes': { text: 'There are unsaved changes.' },
      'read-only': { text: 'Read only: you can view but not edit.' },
      'draft-restored': { text: 'Draft restored: you pick up where you left off.' },
      'field-error': { text: 'Fill in this field.' },
      unknown: (s) => `State "${s}".`,
    },
    region: {
      'side-panel': 'Side panel', 'kpi-strip': 'Indicators', 'search-bar': 'Search', 'decision-area': 'Decision',
      'viewer-toolbar': 'Document bar', filters: 'Filters', 'bulk-actions-bar': 'Bulk actions', toolbar: 'Action bar',
      header: 'Header', summary: 'Summary', 'danger-zone': 'Danger zone', 'quick-view': 'Quick view',
    },
    search: 'Search',
    plainTerms: {
      ses: 'email', smtp: 'email', sha256: '', sha1: '', md5: '', hash: '', token: 'code', uuid: 'code',
      payload: 'data', endpoint: 'address', backend: 'server', worker: 'automatic process', snapshot: 'version',
      tenant: 'account', flag: 'option', rls: '', is_corrente: '', json: 'file', api: 'integration',
    },
  },
};

/** Product text of a language tag (UX.md `content.language`); omitted or unknown → pt-BR. */
export const productText = (tag) => PRODUCT_TEXT[resolveLang(tag) ?? 'pt-BR'];
