// Interface text of the variations comparison page (lib/variations-page.mjs), per page language. `--lang en|pt-BR`
// on `variations.mjs page`; English is the default and pt-BR keeps the page text DSX shipped before the English
// round. Every key exists in both languages; interpolated text is a function. Plain-language problem summaries
// (`plain`) live here too: they are page text, not detector messages.
import { resolveLang } from './lang/index.mjs';

export const PAGE_LANGS = ['en', 'pt-BR'];
export const DEFAULT_PAGE_LANG = 'en';

const lowerFirst = (s) => String(s ?? '').replace(/^\p{Lu}(?!\p{Lu})/u, (c) => c.toLowerCase());
const plural = (n, one, many) => (n === 1 ? one : many);

const EN = {
  html_lang: 'en',
  axis: { screen: 'Screen', flow: 'Flow', behavior: 'Behavior', text: 'Text' },
  axis_lower: { screen: 'screen', flow: 'flow', behavior: 'behavior', text: 'text' },
  part: { state: 'State', dialog: 'Dialog', behavior: 'Behavior' },
  metric: { steps: 'screens', clicks_to_done: 'clicks', dialogs: 'dialogs', primary_actions: 'primary actions', words_on_screen: 'words per screen', decisions: 'decisions' },
  lens: {
    subtract: 'Subtract: a step, field or decision goes away',
    invert: 'Invert: changes who acts or when',
    analogous: 'Borrow: copies what works elsewhere',
    'constraint-first': 'Worst case first: designs for the hard case',
    'object-first': 'Object first: organizes around the thing, not the sequence',
  },
  plain: {
    X1: 'Dash used as a pause in the text', X1b: 'Dash in place of an empty value', X2: 'Two texts glued by a separator',
    X3: 'Helper text that only repeats the title', X4: 'Empty opening that says nothing', X5: 'Period at the end of a label, button or title',
    X6: 'Button with long text or no verb', X7: 'Tooltip that repeats the visible text', X8: 'Field example that only repeats the label',
    X9: 'Explanation in parentheses in a title or button', X10: 'Capital Letters On Every Word', X11: 'Technical term on screen',
    T1: 'More than one primary button in the same area', T2: 'Dialog buttons in the wrong order', T3: 'Screen without a main title',
    T4: 'Field without a label', T5: 'Delete action with a vague label (OK, Yes)', T6: 'Word the product forbids on screen', T7: 'Button that does not say what it does',
    F1: 'Screen with no way out', F2: 'Screen outside the known paths', F3: 'Too many steps to finish', F4: 'Dialog opened on top of another dialog', F5: 'Screen with no way back',
    L1: 'The primary button is not where people expect it', L2: 'Too many elements competing for attention at the top', L3: 'Headings in sizes out of order',
    L4: 'Fields and columns out of alignment', L5: 'Label far from its field, or a scattered group', L6: 'The primary button only shows after scrolling',
    L7: 'Line of text too long to read', L8: 'Click area too small', L9: 'An area expected for this type of screen is missing',
    S1: 'Missing screen for a state (empty, error, loading)', S2: 'Empty or error screen with no way out', S3: 'Error that does not say what to do',
    C1: 'The same action with different names across screens', C2: 'The same button with different looks', C3: 'The same concept with different names',
  },
  today: 'Today',
  delta_same: 'same as today',
  delta_almost: 'practically the same as today',
  delta_better: 'better',
  delta_worse: 'worse',
  delta_sr: (n, more) => `${n} ${more ? 'more' : 'fewer'} than today,`,
  kpis: (m) => [
    { key: 'steps', label: 'Screens', noun: 'screens' },
    { key: 'clicks_to_done', label: m.done_label ? `Clicks to ${m.done_label}` : 'Clicks to finish', noun: m.done_label ? `clicks to ${m.done_label}` : 'clicks to finish' },
    { key: 'words_on_screen', label: 'Words per screen', noun: 'words per screen', tolerance: 0.05 },
    { key: 'resolved', label: 'Problems solved', noun: 'problems solved', higher: true },
  ],
  list: (xs) => (xs.length < 2 ? xs.join('') : `${xs.slice(0, -1).join(', ')} and ${xs.at(-1)}`),
  leads_in: (letter, list) => `${letter} in ${list}`,
  leaders_sentence: (parts) => `Who leads each number: ${parts}.`,
  leaders_none: 'No version improves on today\'s numbers.',
  out_of_registry: 'Problem not in the registry',
  badge_check: 'needs checking',
  badge_ok: 'solved',
  badge_bad: 'still there',
  why_no_measure: 'No automatic measurement: check it on the screen.',
  why_suspect_quoted: (q) => `Gone from here, but the same kind of problem shows up in this version in "${q.join('", "')}": check whether it is acceptable.`,
  why_suspect: 'The same kind of problem shows up elsewhere in this version: check it on the screen.',
  why_persists: 'Still shows up in this version.',
  why_not_registered: 'This problem is not in the module registry.',
  why_flow: 'Depends on the path between screens: check it in the step-by-step.',
  why_consistency: 'Depends on comparing screens with each other: check it in the step-by-step.',
  why_layout: 'The position on screen was not measured: check it in the image.',
  why_review: 'Raised in review: check it by reading the screen.',
  question: (title) => `How to ${lowerFirst(title)} with less work?`,
  where_today: (steps) => `today in ${steps}`,
  done_noun: (label) => (label ? `to ${label}` : 'to finish'),
  who: (letter) => (letter === null ? 'of today' : `of version ${letter}`),
  current_name: 'How it is today',
  zoom_name: (who, step, phase) => `Zoom into the screen ${who} at step ${step}${phase ? `, ${phase}` : ''}`,
  zoom_prefix: /^Zoom into the screen/,
  zoom_alt_prefix: 'Screen',
  unit_image: 'Image',
  unit_version: 'Version',
  no_image: 'no image',
  zoom_tag: 'Zoom',
  of_total: (n) => ` of ${n}`,
  to_check: (n) => `+ ${n} to check`,
  measured_off: (d) => `measured on the screens (initial estimate: ${d})`,
  not_comparable: 'not comparable',
  leads: 'leads',
  gain_current: 'Already exists: nothing to build.',
  cost_current: (n) => `${n} ${plural(n, 'problem', 'problems')} of today ${plural(n, 'remains', 'remain')}.`,
  current_concept: (n) => `${n} ${plural(n, 'screen', 'screens')}, the way it works today.`,
  gains: 'Gains',
  costs: 'Costs',
  see_steps: 'See step by step',
  before: 'Before',
  after: 'After',
  phase_before: 'before',
  phase_after: 'after',
  action_fallback: 'action',
  crop_note: 'The crop shows the part that changed, outlined.',
  marks_note: 'The outlines mark what changed between before and after.',
  click_note: 'Click an image to see the whole screen at actual size.',
  today_step: (step) => `Today · ${step}`,
  pair_name: (letter) => `Today and ${letter} side by side`,
  zoom_pair: 'Zoom into both side by side',
  pair_note: 'The crops show the main part of each screen; zoomed in, they appear whole.',
  no_equivalent: 'Today has no equivalent step.',
  step_of: (n, total) => `Step ${n} of ${total}`,
  prev_step: 'Previous step',
  next_step: 'Next step',
  prev: '← Previous',
  next: 'Next →',
  compare_today: 'Compare with today',
  compare_note: '"Compare with today" applies to every version at once.',
  path_steps: 'Steps of the flow',
  states_behaviors: 'States and behaviors',
  see_findings: 'see on the findings page',
  clicks_mismatch: (n, d) => `The list has ${n} and the summary number says ${d}.`,
  clicks_summary: (n, done) => `The ${n} ${plural(n, 'click', 'clicks')} ${done}`,
  not_comparable_why: (why) => `Not comparable: ${why}`,
  archetype: (t, id) => `Archetype: ${t} (${id}).`,
  catalog_patterns: (list) => `Catalog patterns: ${list}.`,
  principles: (list) => `Principles: ${list}.`,
  lens_line: (l) => `Lens (Forward, USE-10): ${l}.`,
  cited_findings: (list) => `Cited findings: ${list}.`,
  version_code: 'Version code:',
  for_builders: 'For builders',
  bet_rows: (r, lens) => [
    ['For whom', r.audience], ['The bet', r.causal_bet], ['What would prove it wrong', r.counter_hypothesis],
    ['How to test whether it is wrong', r.falsification_test], ['Number that should improve', r.expected_metric], ['What must not get worse', r.guardrail],
    ['Angle of the idea', lens],
  ],
  recommended: (why) => `Recommended by the designer${why ? `: ${why}` : '.'}`,
  why_not_recommended: (t) => `Why it is not the recommended one: ${t}`,
  how_to_know: 'How to know whether it works',
  today_problems: (n) => `Problems of today (${n})`,
  cited_by_versions: (list) => `Findings cited by the versions: ${list}.`,
  what_changes: 'What changes',
  why_may_work: 'Why it may work',
  risks: (n) => `Risks (${n})`,
  solves: (ok, check) => `Problems it solves (${ok} confirmed${check ? `, ${check} to check` : ''})`,
  solves_none: 'This version does not say which problems it solves.',
  new_attention: (n) => `New points of attention (${n})`,
  severe: 'severe',
  attention: 'attention',
  in_steps: (s) => `in ${s}`,
  versions: 'Versions',
  version: 'Version',
  keep_as_is: 'None, keep it as it is',
  which: 'Which one to follow?',
  resumed: 'We restored your previous choice, saved in this browser.',
  clear: 'Clear',
  chosen_version: 'Chosen version',
  choose_error: 'Choose a version before copying.',
  mix_note: 'With mixing on, the choice comes from the parts chosen below. Turn mixing off to choose a whole version.',
  comment: 'Comment',
  comment_ph: 'Why this choice; what to adjust when building',
  who_decides: 'Who decides (required)',
  by_error: 'Say who decides before copying.',
  mix_summary: 'Mix parts of different versions',
  mix_check: 'Use the mix below instead of a whole version',
  mix_warn: 'Mixing can produce an incoherent combination (the text of one version talking about a step another removed): describe the mix in the comment.',
  copy_decision: 'Copy decision',
  after_copy: 'After copying, paste it into the conversation with whoever leads the project (or send it by email). Your choice is saved only in this browser.',
  decision_file: 'Decision file (the same text "Copy decision" copies):',
  decision_file_label: 'Decision file',
  save_as: (cmd) => `To record it in the project, save it as <code>decision.json</code> and run <code>${cmd}</code>.`,
  measured_vs_declared: (l, metric, x, d) => `${l}: ${metric} measured ${x}, declared ${d}`,
  prep_warnings: (w) => `Preparation warnings: ${w}`,
  how_counted: 'How the numbers were counted',
  about_screens: '<b>Screens:</b> distinct screens from the start to the end of the main path; a dialog does not count as a screen.',
  about_clicks: (done) => `<b>Clicks ${done}:</b> clicks on the main path until the task is done. Each version's list is in its details.`,
  about_words: '<b>Words per screen:</b> average of the visible words in the content, measured on the screens (without the product menu and header).',
  about_resolved: (n) => `<b>Problems solved:</b> of the ${n} problems of today cited by the versions, how many the check confirms as solved. They are text, screen and position findings, counted one by one and unweighted (a problem repeated on several screens counts several times). The ones that still need checking are shown alongside and the ones that remain do not count; when what is left to check could change who leads, no version gets the badge.`,
  about_less: 'Less is better, except for problems solved.',
  for_whom: 'For whom:',
  task: 'Task:',
  how_this_counted: 'How this comparison counted:',
  measured_diff: 'Measured differently from declared:',
  nc_numbers: 'Numbers that are not comparable:',
  no_layout: 'The position of elements on screen was not measured in this run: position problems show up as "needs checking".',
  pages: 'Pages',
  same_moment: (step) => `The screens on the cards show the same moment of the flow: step ${step} of today and its equivalent in each version.`,
  title: (t, n, total) => `Variations · ${t}${n > 1 ? ` · page ${n} of ${total}` : ''}`,
  eyebrow_versions: (n) => `${n} ${plural(n, 'version', 'versions')}`,
  summary_label: 'Summary of the versions',
  step_by_step: 'Step by step',
  zoomed: 'Zoomed screen',
  prev_image: 'Previous image',
  next_image: 'Next image',
  actual_size: 'Actual size',
  close: 'Close',
  // embedded script
  js: {
    of: ' of ',
    as_today: 'as today',
    your_mix: 'Your choice: mix (',
    of_today: 'of today',
    of_prefix: 'of ',
    your_choice: 'Your choice: ',
    keep: 'none, keep it as it is',
    no_choice: 'No choice yet.',
    copied: 'Decision copied. Paste it into the conversation with whoever leads the project (or send it by email).',
    copy_failed: 'Could not copy automatically: the decision text is selected below; copy it and paste it into the conversation with whoever leads the project.',
  },
};

const PT = {
  html_lang: 'pt-BR',
  axis: { screen: 'Tela', flow: 'Fluxo', behavior: 'Comportamento', text: 'Texto' },
  axis_lower: { screen: 'tela', flow: 'fluxo', behavior: 'comportamento', text: 'texto' },
  part: { state: 'Estado', dialog: 'Diálogo', behavior: 'Comportamento' },
  metric: { steps: 'telas', clicks_to_done: 'cliques', dialogs: 'diálogos', primary_actions: 'ações principais', words_on_screen: 'palavras por tela', decisions: 'decisões' },
  lens: {
    subtract: 'Tirar: um passo, campo ou decisão some',
    invert: 'Inverter: muda quem age ou quando',
    analogous: 'Emprestar: copia o que funciona em outro lugar',
    'constraint-first': 'Pior caso primeiro: desenha para o caso difícil',
    'object-first': 'Pelo objeto: organiza em volta da coisa, não da sequência',
  },
  plain: {
    X1: 'Travessão usado como pausa no texto', X1b: 'Travessão no lugar de um valor vazio', X2: 'Dois textos colados por um separador',
    X3: 'Texto de apoio que só repete o título', X4: 'Abertura vazia, que não diz nada', X5: 'Ponto final em rótulo, botão ou título',
    X6: 'Botão com texto longo ou sem verbo', X7: 'Dica que repete o texto visível', X8: 'Campo com exemplo que só repete o rótulo',
    X9: 'Explicação entre parênteses em título ou botão', X10: 'Maiúsculas Em Todas As Palavras', X11: 'Termo técnico na tela',
    T1: 'Mais de um botão principal na mesma área', T2: 'Botões do diálogo na ordem trocada', T3: 'Tela sem um título principal',
    T4: 'Campo sem rótulo', T5: 'Ação que apaga com rótulo vago (OK, Sim)', T6: 'Palavra que o produto proíbe na tela', T7: 'Botão que não diz o que faz',
    F1: 'Tela sem saída', F2: 'Tela fora dos caminhos conhecidos', F3: 'Passos demais até concluir', F4: 'Diálogo aberto sobre outro diálogo', F5: 'Tela sem caminho de volta',
    L1: 'O botão principal fica fora do lugar esperado', L2: 'Muitos elementos disputando atenção no topo', L3: 'Títulos em tamanhos fora de ordem',
    L4: 'Campos e colunas desalinhados', L5: 'Rótulo longe do campo ou grupo espalhado', L6: 'O botão principal só aparece rolando a página',
    L7: 'Linha de texto longa demais para ler', L8: 'Área de clique pequena demais', L9: 'Falta uma área esperada para este tipo de tela',
    S1: 'Falta a tela de um estado (vazio, erro, carregando)', S2: 'Tela vazia ou de erro sem saída', S3: 'Erro que não diz o que fazer',
    C1: 'A mesma ação com nomes diferentes entre telas', C2: 'O mesmo botão com aparências diferentes', C3: 'O mesmo conceito com nomes diferentes',
  },
  today: 'Hoje',
  delta_same: 'igual a hoje',
  delta_almost: 'praticamente igual a hoje',
  delta_better: 'melhor',
  delta_worse: 'pior',
  delta_sr: (n, more) => `${n} a ${more ? 'mais' : 'menos'} que hoje,`,
  kpis: (m) => [
    { key: 'steps', label: 'Telas', noun: 'telas' },
    { key: 'clicks_to_done', label: m.done_label ? `Cliques até ${m.done_label}` : 'Cliques até concluir', noun: m.done_label ? `cliques até ${m.done_label}` : 'cliques até concluir' },
    { key: 'words_on_screen', label: 'Palavras por tela', noun: 'palavras por tela', tolerance: 0.05 },
    { key: 'resolved', label: 'Problemas resolvidos', noun: 'problemas resolvidos', higher: true },
  ],
  list: (xs) => (xs.length < 2 ? xs.join('') : `${xs.slice(0, -1).join(', ')} e ${xs.at(-1)}`),
  leads_in: (letter, list) => `${letter} em ${list}`,
  leaders_sentence: (parts) => `Quem lidera cada número: ${parts}.`,
  leaders_none: 'Nenhuma versão melhora os números de hoje.',
  out_of_registry: 'Problema fora do registro',
  badge_check: 'precisa conferir',
  badge_ok: 'resolvido',
  badge_bad: 'continua',
  why_no_measure: 'Sem medição automática: confira na tela.',
  why_suspect_quoted: (q) => `Saiu daqui, mas o mesmo tipo de problema aparece nesta versão em "${q.join('", "')}": confira se é aceitável.`,
  why_suspect: 'O mesmo tipo de problema aparece em outro ponto desta versão: confira na tela.',
  why_persists: 'Ainda aparece nesta versão.',
  why_not_registered: 'Este problema não está no registro do módulo.',
  why_flow: 'Depende do caminho entre as telas: confira no passo a passo.',
  why_consistency: 'Depende de comparar telas entre si: confira no passo a passo.',
  why_layout: 'A posição na tela não foi medida: confira na imagem.',
  why_review: 'Apontado em revisão: confira lendo a tela.',
  question: (title) => `Como ${lowerFirst(title)} com menos trabalho?`,
  where_today: (steps) => `hoje em ${steps}`,
  done_noun: (label) => (label ? `até ${label}` : 'até concluir'),
  who: (letter) => (letter === null ? 'de hoje' : `da versão ${letter}`),
  current_name: 'Como é hoje',
  zoom_name: (who, step, phase) => `Ampliar a tela ${who} no passo ${step}${phase ? `, ${phase}` : ''}`,
  zoom_prefix: /^Ampliar a tela/,
  zoom_alt_prefix: 'Tela',
  unit_image: 'Imagem',
  unit_version: 'Versão',
  no_image: 'sem imagem',
  zoom_tag: 'Ampliar',
  of_total: (n) => ` de ${n}`,
  to_check: (n) => `+ ${n} a conferir`,
  measured_off: (d) => `medido nas telas (estimativa inicial: ${d})`,
  not_comparable: 'não comparável',
  leads: 'lidera',
  gain_current: 'Já existe: nada a construir.',
  cost_current: (n) => `${n} problema${n === 1 ? '' : 's'} de hoje continua${n === 1 ? '' : 'm'}.`,
  current_concept: (n) => `${n} telas, do jeito que funciona hoje.`,
  gains: 'Ganha',
  costs: 'Custa',
  see_steps: 'Ver passo a passo',
  before: 'Antes',
  after: 'Depois',
  phase_before: 'antes',
  phase_after: 'depois',
  action_fallback: 'ação',
  crop_note: 'O recorte mostra a parte que mudou, contornada.',
  marks_note: 'Os contornos marcam o que mudou entre antes e depois.',
  click_note: 'Clique numa imagem para ver a tela inteira, no tamanho real.',
  today_step: (step) => `Hoje · ${step}`,
  pair_name: (letter) => `Hoje e ${letter} lado a lado`,
  zoom_pair: 'Ampliar as duas lado a lado',
  pair_note: 'Os recortes mostram a parte principal de cada tela; ampliadas, aparecem inteiras.',
  no_equivalent: 'Hoje não tem passo equivalente.',
  step_of: (n, total) => `Passo ${n} de ${total}`,
  prev_step: 'Passo anterior',
  next_step: 'Próximo passo',
  prev: '← Anterior',
  next: 'Próximo →',
  compare_today: 'Comparar com hoje',
  compare_note: '"Comparar com hoje" vale para todas as versões ao mesmo tempo.',
  path_steps: 'Passos do fluxo',
  states_behaviors: 'Estados e comportamentos',
  see_findings: 'ver na página de achados',
  clicks_mismatch: (n, d) => `A lista tem ${n} e o número do resumo diz ${d}.`,
  clicks_summary: (n, done) => `Os ${n} cliques ${done}`,
  not_comparable_why: (why) => `Não comparável: ${why}`,
  archetype: (t, id) => `Arquétipo: ${t} (${id}).`,
  catalog_patterns: (list) => `Padrões do catálogo: ${list}.`,
  principles: (list) => `Princípios: ${list}.`,
  lens_line: (l) => `Lente (Forward, USE-10): ${l}.`,
  cited_findings: (list) => `Achados citados: ${list}.`,
  version_code: 'Código da versão:',
  for_builders: 'Para quem constrói',
  bet_rows: (r, lens) => [
    ['Para quem', r.audience], ['A aposta', r.causal_bet], ['O que provaria o contrário', r.counter_hypothesis],
    ['Como testar se está errada', r.falsification_test], ['Número que deve melhorar', r.expected_metric], ['O que não pode piorar', r.guardrail],
    ['Ângulo da ideia', lens],
  ],
  recommended: (why) => `Recomendada por quem desenhou${why ? `: ${why}` : '.'}`,
  why_not_recommended: (t) => `Por que não é a recomendada: ${t}`,
  how_to_know: 'Como saber se funciona',
  today_problems: (n) => `Problemas de hoje (${n})`,
  cited_by_versions: (list) => `Achados citados pelas versões: ${list}.`,
  what_changes: 'O que muda',
  why_may_work: 'Por que pode funcionar',
  risks: (n) => `Riscos (${n})`,
  solves: (ok, check) => `Problemas que resolve (${ok} confirmado${ok === 1 ? '' : 's'}${check ? `, ${check} a conferir` : ''})`,
  solves_none: 'Esta versão não diz quais problemas resolve.',
  new_attention: (n) => `Novos pontos de atenção (${n})`,
  severe: 'grave',
  attention: 'atenção',
  in_steps: (s) => `em ${s}`,
  versions: 'Versões',
  version: 'Versão',
  keep_as_is: 'Nenhuma, manter como está',
  which: 'Qual seguir?',
  resumed: 'Retomamos sua escolha anterior, salva neste navegador.',
  clear: 'Limpar',
  chosen_version: 'Versão escolhida',
  choose_error: 'Escolha uma versão antes de copiar.',
  mix_note: 'Com a mistura ligada, a escolha vem das partes escolhidas abaixo. Desligue a mistura para escolher uma versão inteira.',
  comment: 'Comentário',
  comment_ph: 'Por que esta escolha; o que ajustar ao construir',
  who_decides: 'Quem decide (obrigatório)',
  by_error: 'Diga quem decide antes de copiar.',
  mix_summary: 'Misturar partes de versões diferentes',
  mix_check: 'Usar a mistura abaixo em vez de uma versão inteira',
  mix_warn: 'Misturar pode dar uma combinação incoerente (o texto de uma versão falando de um passo que outra tirou): descreva a mistura no comentário.',
  copy_decision: 'Copiar decisão',
  after_copy: 'Depois de copiar, cole na conversa com quem conduz o projeto (ou envie por e-mail). Sua escolha fica salva só neste navegador.',
  decision_file: 'Arquivo da decisão (o mesmo texto que "Copiar decisão" copia):',
  decision_file_label: 'Arquivo da decisão',
  save_as: (cmd) => `Para gravar no projeto, salve como <code>decision.json</code> e rode <code>${cmd}</code>.`,
  measured_vs_declared: (l, metric, x, d) => `${l}: ${metric} medido ${x}, declarado ${d}`,
  prep_warnings: (w) => `Avisos da preparação: ${w}`,
  how_counted: 'Como os números foram contados',
  about_screens: '<b>Telas:</b> telas diferentes do começo ao fim do caminho principal; diálogo não conta como tela.',
  about_clicks: (done) => `<b>Cliques ${done}:</b> cliques no caminho principal até o fim da tarefa. A lista de cada versão está nos detalhes dela.`,
  about_words: '<b>Palavras por tela:</b> média das palavras visíveis no conteúdo, medida nas telas (sem o menu e o cabeçalho do produto).',
  about_resolved: (n) => `<b>Problemas resolvidos:</b> dos ${n} problemas de hoje citados pelas versões, quantos a verificação confirma como resolvidos. São achados de texto, de tela e de posição, contados um a um e sem peso (um problema que se repete em várias telas conta várias vezes). Os que ainda precisam de conferência aparecem ao lado e os que continuam não contam; quando o que falta conferir pode mudar quem lidera, nenhuma versão leva o selo.`,
  about_less: 'Menos é melhor, exceto em problemas resolvidos.',
  for_whom: 'Para quem:',
  task: 'Tarefa:',
  how_this_counted: 'Como esta comparação contou:',
  measured_diff: 'Medido diferente do declarado:',
  nc_numbers: 'Números não comparáveis:',
  no_layout: 'A posição dos elementos na tela não foi medida nesta geração: problemas de posição aparecem como "precisa conferir".',
  pages: 'Páginas',
  same_moment: (step) => `As telas dos cartões mostram o mesmo momento do fluxo: o passo ${step} de hoje e o equivalente em cada versão.`,
  title: (t, n, total) => `Variações · ${t}${n > 1 ? ` · página ${n} de ${total}` : ''}`,
  eyebrow_versions: (n) => `${n} versões`,
  summary_label: 'Resumo das versões',
  step_by_step: 'Passo a passo',
  zoomed: 'Tela ampliada',
  prev_image: 'Imagem anterior',
  next_image: 'Próxima imagem',
  actual_size: 'Tamanho real',
  close: 'Fechar',
  js: {
    of: ' de ',
    as_today: 'como hoje',
    your_mix: 'Sua escolha: mistura (',
    of_today: 'de hoje',
    of_prefix: 'de ',
    your_choice: 'Sua escolha: ',
    keep: 'nenhuma, manter como está',
    no_choice: 'Nenhuma escolha ainda.',
    copied: 'Decisão copiada. Cole na conversa com quem conduz o projeto (ou envie por e-mail).',
    copy_failed: 'Não deu para copiar sozinho: o texto da decisão está selecionado abaixo; copie e cole na conversa com quem conduz o projeto.',
  },
};

export const STRINGS = Object.freeze({ en: EN, 'pt-BR': PT });

/** Normalized page language (`pt`, `pt-br`, `en-US`… accepted); null when the tag is not a page language. */
export function pageLang(tag) {
  if (tag === undefined || tag === null || tag === '') return DEFAULT_PAGE_LANG;
  const l = resolveLang(tag);
  return l && PAGE_LANGS.includes(l) ? l : null;
}

/** Strings for a language tag (unknown → English). */
export const stringsFor = (lang) => STRINGS[pageLang(lang) ?? DEFAULT_PAGE_LANG];
